# Generated by Django 2.2.12 on 2020-05-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='DummyUser', max_length=255),
            preserve_default=False,
        ),
    ]
