# Generated by Django 2.2.12 on 2020-05-28 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
        ('language', '0001_initial'),
        ('account', '0002_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Contributors's first name", max_length=255)),
                ('nick_name', models.CharField(help_text="Contributors's Nick name", max_length=50)),
                ('bio', models.TextField(help_text='Contributors bio')),
                ('skype_name', models.CharField(help_text='skype name', max_length=50)),
                ('mobile_number', models.CharField(help_text='Contact(Mobile) number', max_length=15)),
                ('profile_image', models.ImageField(blank=True, db_column='profile_picture', null=True, upload_to='uploads/users/profile/')),
                ('github_account', models.CharField(help_text='github.com account profile url.', max_length=500)),
                ('stackoverflow_account', models.CharField(help_text='stackoverflow.com account profile url.', max_length=500)),
                ('personal_blog_url', models.CharField(help_text='Personal blog or website url.', max_length=500)),
                ('languages', models.ManyToManyField(help_text='User may know multiple language.', related_name='language_profiles', to='language.Language')),
                ('technologies', models.ManyToManyField(help_text='User may know multiple technology.', related_name='tech_profiles', to='technology.Technology')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
