# Generated by Django 2.2.12 on 2020-05-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/language/'),
        ),
    ]
