# Generated by Django 2.2.12 on 2020-05-11 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0002_auto_20200511_1229'),
        ('technology', '0003_auto_20200511_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Components',
                'verbose_name': 'Component',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('git_url', models.URLField(null=True, verbose_name='github URL')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components_detail', related_query_name='component_detail', to='component.Component')),
                ('language', models.ManyToManyField(related_name='languages', to='language.Language')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='technology.Technology')),
            ],
            options={
                'verbose_name_plural': 'Component Details',
                'verbose_name': 'Component Detail',
            },
        ),
        migrations.CreateModel(
            name='DetailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='uploads/content/images/')),
                ('component_detail_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='image', to='component.Detail', verbose_name='component')),
            ],
            options={
                'verbose_name_plural': 'Component Images',
                'verbose_name': 'Component Image',
            },
        ),
    ]
