# Generated by Django 2.2.12 on 2020-05-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile'),
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='contributors',
            field=models.ManyToManyField(help_text='Developers who worked on component', related_name='component_contributors', to='account.Profile'),
        ),
    ]
