# Generated by Django 2.2.12 on 2020-05-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/technology/')),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'verbose_name': 'Technology',
            },
        ),
    ]
